name: Release Terrabutler

on:  
  push:
    tags:
      - '*'

jobs:
  release-terrabutler:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get Current Tag
        uses: WyriHaximus/github-action-get-previous-tag@master
        id: tag
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Build Python Module
        run: |
          pip install -r requirements.txt pyinstaller
          pyinstaller --clean -y --dist ./dist/terrabutler --workpath /tmp terrabutler/terrabutler.spec
          mv dist/terrabutler/terrabutler dist/terrabutler/dist
      - name: Copy needed files to build directory
        run: |
          cp README.md dist/terrabutler
          cp LICENSE dist/terrabutler
          cp scripts/install dist/terrabutler
      - name: Create archive of build (.tar.gz)
        uses: sibiraj-s/action-archiver@v1
        with:
          working-directory: "./"
          path: "dist"
          format: tar
          gzip: true
          output: terrabutler-linux-x86_64-${{ steps.tag.outputs.tag }}.tar.gz
      - name: Create duplicate archive with latest
        run:
          cp terrabutler-linux-x86_64-${{ steps.tag.outputs.tag }}.tar.gz terrabutler-linux-x86_64-latest.tar.gz
      - name: Add artifact to Release
        uses: softprops/action-gh-release@v1
        with:
          files: terrabutler-linux-x86_64-${{ steps.tag.outputs.tag }}.tar.gz
      - name: Upload artifact to S3 bucket
        uses: zdurham/s3-upload-github-action@master
        with:
          args: --acl public-read
        env:
          FILE: ./terrabutler-linux-x86_64-${{ steps.tag.outputs.tag }}.tar.gz
          AWS_REGION: ${{ secrets.AWS_REGION }}
          S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          S3_KEY: ${{ secrets.AWS_S3_KEY }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Upload as latest artifact to S3 bucket
        uses: zdurham/s3-upload-github-action@master
        with:
          args: --acl public-read
        env:
          FILE: ./terrabutler-linux-x86_64-latest.tar.gz
          AWS_REGION: ${{ secrets.AWS_REGION }}
          S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          S3_KEY: ${{ secrets.AWS_S3_KEY }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}