name: Release Terrabutler

on:  
  push:
    tags:
      - '*'

jobs:
  release-terrabutler:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get Current Tag
        uses: WyriHaximus/github-action-get-previous-tag@master
        id: tag
      - name: Setup Pyhton
        uses: actions/setup-python@v3
        with:
          python-version: 3.10
      - name: Build Python Module
        uses: JackMcKew/pyinstaller-action-linux@main
        with:
          path: terrabutler
      - name: Copy needed files to build directory
        run: |
          ls -lha
          cp README.md terrabutler/dist/linux
      - name: Create archive of build (.tar.gz)
        uses: sibiraj-s/action-archiver@v1
        with:
          working-directory: "./"
          path: "terrabutler/dist/linux"
          format: tar
          gzip: true
          output: terrabutler-${{ runner.os }}-${{ runner.arch }}-${{ steps.tag.outputs.tag }}.tar.gz
      - name: Add artifact to Release
        uses: softprops/action-gh-release@v1
        with:
          files: terrabutler-${{ runner.os }}-${{ runner.arch }}-${{ steps.tag.outputs.tag }}.tar.gz
      - name: Upload artifact to S3 bucket
        uses: zdurham/s3-upload-github-action@master
        with:
          args: --acl public-read
        env:
          FILE: ./terrabutler-${{ runner.os }}-${{ runner.arch }}-${{ steps.tag.outputs.tag }}.tar.gz
          AWS_REGION: ${{ secrets.AWS_REGION }}
          S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          S3_KEY: ${{ secrets.AWS_S3_KEY }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}