name: Test Code

on:
  pull_request:
    branches:
      - master

jobs:
  lint-python:
    name: Lint Python
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Lint Python (Flake8)
        uses: grantmcconnaughey/lintly-flake8-github-action@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}